/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package classes.View;

import classes.DBManagment.DBManager;
import classes.Peptido;
import java.awt.Image;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author leisy
 */
public class DescripView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DescripView.class.getName());

    /**
     * Creates new form DescripView
     * @param user
     * @param pepList
     */
    public DescripView(String user, ArrayList<Peptido> pepList) {
        initComponents();
        setTableModel(pepList);
        
        this.pepList=pepList;
        this.user = user;
        
        if("consultor".equals(user)){
            tittleLabel.setText("   Visualizador de Datos de Péptidos");
            addButton.setVisible(false);
        } else {
            tittleLabel.setText("   Editor de Datos de Péptidos");
        }
        
        Icon  i = addButton.getIcon();
        ImageIcon icon = (ImageIcon)i;
        Image image = icon.getImage().getScaledInstance(addButton.getWidth(), addButton.getHeight(), Image.SCALE_SMOOTH);
        addButton.setIcon(new ImageIcon(image));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        TopPanel = new javax.swing.JPanel();
        tittleLabel = new javax.swing.JLabel();
        addButton = new javax.swing.JToggleButton();
        exportButton = new javax.swing.JButton();
        searchField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pepListTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Base de Datos de Péptidos");
        setBackground(new java.awt.Color(231, 212, 187));

        MainPanel.setBackground(new java.awt.Color(133, 120, 97));
        MainPanel.setForeground(new java.awt.Color(16, 18, 17));

        TopPanel.setBackground(new java.awt.Color(231, 212, 187));
        TopPanel.setName(""); // NOI18N

        tittleLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tittleLabel.setText("   Visualizador de Datos de Péptidos");

        addButton.setBackground(new java.awt.Color(231, 212, 187));
        addButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add_icon_no_bg.png"))); // NOI18N
        addButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(133, 120, 97), 3));
        addButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addButtonMouseClicked(evt);
            }
        });
        addButton.addActionListener(this::addButtonActionPerformed);

        exportButton.setBackground(new java.awt.Color(231, 212, 187));
        exportButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icono_39x39.png"))); // NOI18N
        exportButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(133, 120, 97), 3));
        exportButton.addActionListener(this::exportButtonActionPerformed);

        searchField.setToolTipText("");
        searchField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchFieldFocusGained(evt);
            }
        });
        searchField.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            public void changedUpdate(javax.swing.event.DocumentEvent e) { applySearch(); }
            public void removeUpdate(javax.swing.event.DocumentEvent e) { applySearch(); }
            public void insertUpdate(javax.swing.event.DocumentEvent e) { applySearch(); }
        });

        jLabel1.setText("Buscar por nombre:");

        javax.swing.GroupLayout TopPanelLayout = new javax.swing.GroupLayout(TopPanel);
        TopPanel.setLayout(TopPanelLayout);
        TopPanelLayout.setHorizontalGroup(
            TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopPanelLayout.createSequentialGroup()
                .addComponent(tittleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchField, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        TopPanelLayout.setVerticalGroup(
            TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(tittleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(TopPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchField, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addContainerGap())
        );

        pepListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "Nombre", "Secuencia", "Longitud", "Peso", "Carga Neta", "Hidrofobicidad", "Es Natural", "Estado de Verificación", "Organismo Fuente"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Boolean.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(pepListTable);

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TopPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TopPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        AddPeptidoDialog aPD = new AddPeptidoDialog(this, true);
        aPD.setVisible(true);
        // Refrescar la lista desde la base de datos
        DBManager dbMan = new DBManager();
        pepList.clear();
        dbMan.FillPepArray(pepList);
        // Aplicar el filtro actual o mostrar todos
        applySearch(); // reutiliza el método de búsqueda
    }//GEN-LAST:event_addButtonActionPerformed

    private void addButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addButtonMouseClicked

    }//GEN-LAST:event_addButtonMouseClicked

    private void searchFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchFieldFocusGained

    }//GEN-LAST:event_searchFieldFocusGained

    private void exportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportButtonActionPerformed
        exportToExcel();
    }//GEN-LAST:event_exportButtonActionPerformed
    
    private void setTableModel(ArrayList<Peptido> listToShow) {
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(new Object[]{
            "ID", "Secuencia", "Nombre", "Longitud",
            "Peso molecular", "Carga neta", "Hidrofobicidad",
            "Natural", "Estado de verificación", "Organismo fuente"
        });

        for (Peptido p : listToShow) {
            model.addRow(new Object[]{
                p.id, p.secuencia, p.nombre_principal,
                p.longitud, p.peso_molecular, p.carga_neta,
                p.hidrofobicidad, p.es_natural,
                p.estado_verificacion, p.organismo_fuente
            });
        }
        pepListTable.setModel(model);
    }
    
    private void applySearch() {
        String query = searchField.getText().trim().toLowerCase();
        ArrayList<Peptido> filtered = new ArrayList<>();
        if (query.isEmpty()) {
            filtered = new ArrayList<>(pepList); // copia de la lista completa
        } else {
            for (Peptido p : pepList) {
                if (p.nombre_principal != null && p.nombre_principal.toLowerCase().contains(query)) {
                    filtered.add(p);
                }
            }
        }
        setTableModel(filtered);
    }
    
    private void exportToExcel() {
        // Obtener los datos actuales de la tabla (filtrados o no)
        DefaultTableModel model = (DefaultTableModel) pepListTable.getModel();
        int rowCount = model.getRowCount();
        int colCount = model.getColumnCount();

        // Crear libro de Excel
        XSSFWorkbook workbook = new XSSFWorkbook();
        XSSFSheet sheet = workbook.createSheet("Péptidos");

        // Crear fila de encabezados
        Row headerRow = sheet.createRow(0);
        for (int i = 0; i < colCount; i++) {
            Cell cell = headerRow.createCell(i);
            cell.setCellValue(model.getColumnName(i));
        }

        // Llenar datos
        for (int rowIdx = 0; rowIdx < rowCount; rowIdx++) {
            Row row = sheet.createRow(rowIdx + 1);
            for (int colIdx = 0; colIdx < colCount; colIdx++) {
                Object value = model.getValueAt(rowIdx, colIdx);
                Cell cell = row.createCell(colIdx);
                if (value instanceof Integer) {
                    cell.setCellValue((Integer) value);
                } else if (value instanceof Double) {
                    cell.setCellValue((Double) value);
                } else if (value instanceof Boolean) {
                    cell.setCellValue((Boolean) value);
                } else if (value != null) {
                    cell.setCellValue(value.toString());
                } else {
                    cell.setCellValue("");
                }
            }
        }

        // Ajustar ancho de columnas automáticamente
        for (int i = 0; i < colCount; i++) {
            sheet.autoSizeColumn(i);
        }

        // Mostrar diálogo para guardar archivo
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setSelectedFile(new File("peptidos_export.xlsx"));
        int result = fileChooser.showSaveDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            // Asegurar extensión .xlsx
            if (!file.getName().toLowerCase().endsWith(".xlsx")) {
                file = new File(file.getAbsolutePath() + ".xlsx");
            }
            try (FileOutputStream fos = new FileOutputStream(file)) {
                workbook.write(fos);
                workbook.close();
                JOptionPane.showMessageDialog(this, "Exportación exitosa a:\n" + file.getAbsolutePath());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error al exportar: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                logger.log(java.util.logging.Level.SEVERE, "Error exportando a Excel", e);
            }
        } else {
            try {
                workbook.close();
            } catch (IOException ex) {
                // ignorar
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
//        DBManager db = new DBManager(pepList);
        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> {
//            new DescripView(user).setVisible(true);
//        });
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel TopPanel;
    private javax.swing.JToggleButton addButton;
    private javax.swing.JButton exportButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable pepListTable;
    private javax.swing.JTextField searchField;
    private javax.swing.JLabel tittleLabel;
    // End of variables declaration//GEN-END:variables
    private ArrayList<Peptido> pepList = new ArrayList<>();
    private String user;
}
